### ISSUE TITLE
Agregar componente de reuniones

### ISSUE THREAD

**Issue by vrnicolas** [Fedeorlandau/protojuego#2]
Se debe agregar un componente para determinar las reuniones que se deseen introducir durante el sprint
Cada reunion tiene una carga de horas en el sprint
Reuniones tipo:
Daily:
Semanal
Analysis
Capacitaciones a los usuarios

**Comment by dario-javier-rick** [comment]
Chicos, esto tiene que ver con la simulación. Cualquier duda o comentario avisen

**Comment by Fedeorlandau** [comment]
Done
